workspace = { members = ["web"] }
[package]
name = "ankizh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
genanki-rs = "0.4"
lyon_path = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

